DELETE FROM `Digital_Store`.`ALL_IN_ONE_AND_LAPTOP` WHERE `ID`='3';

DELETE FROM `Digital_Store`.`MOBILE_AND_TABLET` WHERE `ID`='6';

DELETE FROM `Digital_Store`.`SMART_WATCH` WHERE `ID`='8';

DELETE FROM `Digital_Store`.`PRODUCT` WHERE `ID`='3';
DELETE FROM `Digital_Store`.`PRODUCT` WHERE `ID`='6';
DELETE FROM `Digital_Store`.`PRODUCT` WHERE `ID`='8';