SELECT	B.PRODUCT_ID, B.BUYS_Date, B.BUYS_Time, P.PRODUCT_Code, P.PRODUCT_Name, P.Manufacturer, P.Operating_System, P.CEO_SSN, P.IMPORTS_Date, P.IMPORTS_Time
FROM	BUYS AS B, PRODUCT AS P
WHERE	B.PRODUCT_ID = P.ID;