CREATE VIEW TEMP1 AS
SELECT	sum(P.Sales_Price) AS Profit
FROM	BUYS AS B, PRODUCT AS P
WHERE	B.PRODUCT_ID = P.ID;

CREATE VIEW TEMP2 AS
SELECT	sum(P.Purchase_Price) AS S_P
FROM	PRODUCT AS P;

CREATE VIEW TEMP3 AS
SELECT	sum(Amount) AS A
FROM	PAYMENT_STUFF;

SELECT	sum(Captal - Profit - S_P - A) AS Stock
FROM	TEMP1, TEMP2, TEMP3, CEO
WHERE	Date_Of_End IS NULL;

DROP VIEW TEMP1;

DROP VIEW TEMP2;

DROP VIEW TEMP3;

