-- MySQL Script generated by MySQL Workbench
-- Fri Jul 28 16:39:01 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Digital_Store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Digital_Store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Digital_Store` DEFAULT CHARACTER SET utf8 ;
USE `Digital_Store` ;

-- -----------------------------------------------------
-- Table `Digital_Store`.`PERSON`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Digital_Store`.`PERSON` (
  `SSN` INT UNSIGNED NOT NULL,
  `First_Name` VARCHAR(45) NOT NULL,
  `Last_Name` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Sex` CHAR(1) NOT NULL DEFAULT 'M',
  `Date_Of_Birth` DATE NOT NULL,
  `Address` VARCHAR(100) NULL,
  `Home_Phone` VARCHAR(16) NULL,
  `Mobile_Phone` VARCHAR(16) NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SSN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Digital_Store`.`CEO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Digital_Store`.`CEO` (
  `SSN` INT UNSIGNED NOT NULL,
  `Legal_Identifier` CHAR(20) NOT NULL,
  `Captal` INT NOT NULL DEFAULT 1000000,
  `Date_Of_Start` DATE NOT NULL,
  `Time_Of_Start` TIME NOT NULL,
  `Date_Of_End` DATE NULL,
  `Time_Of_End` TIME NULL,
  PRIMARY KEY (`SSN`),
  UNIQUE INDEX `Legal_Identifier_UNIQUE` (`Legal_Identifier` ASC),
  CONSTRAINT `SSN_F_1`
    FOREIGN KEY (`SSN`)
    REFERENCES `Digital_Store`.`PERSON` (`SSN`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Digital_Store`.`CUSTOMER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Digital_Store`.`CUSTOMER` (
  `SSN` INT UNSIGNED NOT NULL,
  `Bank_Card_Number` CHAR(16) NOT NULL,
  PRIMARY KEY (`SSN`),
  CONSTRAINT `SSN_F_2`
    FOREIGN KEY (`SSN`)
    REFERENCES `Digital_Store`.`PERSON` (`SSN`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Digital_Store`.`PAYMENT_STUFF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Digital_Store`.`PAYMENT_STUFF` (
  `ID` CHAR(10) NOT NULL,
  `Amount` INT UNSIGNED NOT NULL DEFAULT 10,
  `CEO_SSN` INT UNSIGNED NULL,
  `Pay_Date` DATE NOT NULL,
  `Pay_Time` TIME NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `CEO_SSN_F_1_idx` (`CEO_SSN` ASC),
  CONSTRAINT `CEO_SSN_F_1`
    FOREIGN KEY (`CEO_SSN`)
    REFERENCES `Digital_Store`.`CEO` (`SSN`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Digital_Store`.`BILL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Digital_Store`.`BILL` (
  `ID` CHAR(10) NOT NULL,
  `Typee` VARCHAR(45) NOT NULL DEFAULT 'Telephone',
  PRIMARY KEY (`ID`),
  CONSTRAINT `ID_F_1`
    FOREIGN KEY (`ID`)
    REFERENCES `Digital_Store`.`PAYMENT_STUFF` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Digital_Store`.`TAX`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Digital_Store`.`TAX` (
  `ID` CHAR(10) NOT NULL,
  `Groupp` VARCHAR(45) NOT NULL DEFAULT 'Mid_Year',
  PRIMARY KEY (`ID`),
  CONSTRAINT `ID_F_2`
    FOREIGN KEY (`ID`)
    REFERENCES `Digital_Store`.`PAYMENT_STUFF` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Digital_Store`.`PRODUCT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Digital_Store`.`PRODUCT` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Codee` CHAR(15) NOT NULL,
  `Namee` VARCHAR(45) NOT NULL,
  `Manufacturer` VARCHAR(45) NOT NULL,
  `Operating_System` VARCHAR(45) NULL,
  `Data_Of_Production` DATE NOT NULL,
  `Purchase_Price` INT NOT NULL,
  `Sales_Price` INT NOT NULL,
  `CEO_SSN` INT UNSIGNED NULL,
  `Datee` DATE NOT NULL,
  `Timee` TIME NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `CEO_SSN_F_2_idx` (`CEO_SSN` ASC),
  CONSTRAINT `CEO_SSN_F_2`
    FOREIGN KEY (`CEO_SSN`)
    REFERENCES `Digital_Store`.`CEO` (`SSN`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Digital_Store`.`ALL_IN_ONE_AND_LAPTOP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Digital_Store`.`ALL_IN_ONE_AND_LAPTOP` (
  `ID` INT UNSIGNED NOT NULL,
  `CPU` VARCHAR(45) NOT NULL,
  `GPU` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `ID_F_3`
    FOREIGN KEY (`ID`)
    REFERENCES `Digital_Store`.`PRODUCT` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Digital_Store`.`MOBILE_AND_TABLET`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Digital_Store`.`MOBILE_AND_TABLET` (
  `ID` INT UNSIGNED NOT NULL,
  `Number_Of_SIM_Cards` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  CONSTRAINT `ID_F_4`
    FOREIGN KEY (`ID`)
    REFERENCES `Digital_Store`.`PRODUCT` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Digital_Store`.`SMART_WATCH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Digital_Store`.`SMART_WATCH` (
  `ID` INT UNSIGNED NOT NULL,
  `Body_Material` VARCHAR(45) NOT NULL DEFAULT 'Aluminum',
  `Band_Type` VARCHAR(45) NOT NULL DEFAULT 'Normal',
  `Water_Resistanancy` CHAR(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (`ID`),
  CONSTRAINT `ID_F_5`
    FOREIGN KEY (`ID`)
    REFERENCES `Digital_Store`.`PRODUCT` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Digital_Store`.`BUYS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Digital_Store`.`BUYS` (
  `SSN` INT UNSIGNED NOT NULL,
  `ID` INT UNSIGNED NOT NULL,
  `Delivery_Address` VARCHAR(100) NOT NULL,
  `Datee` DATE NOT NULL,
  `Timee` TIME NOT NULL,
  PRIMARY KEY (`SSN`, `ID`),
  INDEX `ID_F_6_idx` (`ID` ASC),
  CONSTRAINT `SSN_F_3`
    FOREIGN KEY (`SSN`)
    REFERENCES `Digital_Store`.`CUSTOMER` (`SSN`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `ID_F_6`
    FOREIGN KEY (`ID`)
    REFERENCES `Digital_Store`.`PRODUCT` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
